# ===== Global simulation knobs =====
tx_cost_mJ: 0.02     # per hop transmit cost added in both systems

traffic:
  num_messages: 300
  size_kB: 1

# ===== System-1 (vulnerable) =====
system1:
  allow_direct_link: false     # baseline forces via GW (enforced in runner)

attacker:
  placement: "gateway"         # "gateway" | "global" | [["devA","gw"],["gw","devB"]]
  success_prob: 1.0            # 1.0 = every observed msg is intercepted
  rng_seed: 42

# ===== System-2 (secure) =====
system2:
  # Lightweight overheads
  auth_overhead_ms: 3
  kim_overhead_ms: 5

  # KIM constellation size
  M: 16

  # Channel reciprocity keygen (TDD)
  key_bits: 128
  csi_len: 256
  csi_noise: 0.05

  # Physical-layer stress
  multipath_strength: 0.3        # 0..1 (0 disables)
  pilot_contamination: 0.0       # 0..1 (0 disables)

  # Key-integrated modulation dither (camouflage)
  dither_strength: 0.50      # was 0.30 — stronger key-driven dither → harder to detect

  # Very lightweight energy model (mJ, µJ, nJ units converted in code)
  energy:
    handshake_uj: 50
    kim_map_uj: 0.02
    tx_bit_nj: 1.0
    pkt_bits: 1024

# Gateway Intelligence / ESS
ess:
  rssi_window: 50
  rssi_z_thresh: 3.0
  csi_agree_thresh: 0.75

# Eavesdropper (System-2) — BER & detectability model
attacker2:
  snr_db: 18
  antennas: 1
  rng_seed: 42
  detect_base_threshold: 0.20 # was 0.25 — lower base → reduces Eve's detect probability

# Optional jammer (active attacker)
jammer:
  enabled: false
  duty_cycle: 0.1
  snr_penalty_db: 6.0
